# Generated by Django 2.2.4 on 2019-08-09 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Synnintekija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etunimi', models.CharField(max_length=100)),
                ('sukunimi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Syntilaatu',
            fields=[
                ('laatu_nimi', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syntilaatu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TunnustettuSynti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpl', models.SmallIntegerField()),
                ('laatu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synnit.Syntilaatu')),
                ('tekija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synnit.Synnintekija')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tunnustettusynti',
            constraint=models.UniqueConstraint(fields=('tekija', 'laatu'), name='kyrsa'),
        ),
    ]
